### ISSUE TITLE
FUll Complete dont work

### ISSUE THREAD

**Issue by Justin99b** [kayler-renslow/arma-intellij-plugin#49] opened 2017-05-29 16:31 UTC
strg + space does not work for al things like hint does not work.

so ... i cant use it :(

PLEASE HELP
Plugin Version: 1.0.8

Index: 0, Size: 0

java.lang.IndexOutOfBoundsException: Index: 0, Size: 0
	at java.util.ArrayList.rangeCheck(ArrayList.java:653)
	at java.util.ArrayList.get(ArrayList.java:429)
	at com.kaylerrenslow.a3plugin.lang.sqf.psi.SQFPsiUtil.createElement(SQFPsiUtil.java:247)
	at com.kaylerrenslow.a3plugin.lang.sqf.providers.CompletionAdders.addCommands(CompletionAdders.java:45)
	at com.kaylerrenslow.a3plugin.lang.sqf.providers.SQFCompletionProvider.addVariablesAndCommands(SQFCompletionProvider.java:131)
	at com.kaylerrenslow.a3plugin.lang.sqf.providers.SQFCompletionProvider.completeCurrentWord(SQFCompletionProvider.java:103)
	at com.kaylerrenslow.a3plugin.lang.sqf.providers.SQFCompletionProvider.addCompletions(SQFCompletionProvider.java:71)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:138)
	at com.intellij.codeInsight.completion.CompletionResultSet.runRemainingContributors(CompletionResultSet.java:131)
	at com.intellij.codeInsight.template.impl.LiveTemplateCompletionContributor$2.addCompletions(LiveTemplateCompletionContributor.java:88)
	at com.intellij.codeInsight.completion.CompletionProvider.addCompletionVariants(CompletionProvider.java:36)
	at com.intellij.codeInsight.completion.CompletionContributor.fillCompletionVariants(CompletionContributor.java:151)
	at com.intellij.codeInsight.completion.CompletionService.getVariantsFromContributors(CompletionService.java:81)
	at com.intellij.codeInsight.completion.CompletionService.performCompletion(CompletionService.java:110)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.calculateItems(CompletionProgressIndicator.java:831)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator.access$600(CompletionProgressIndicator.java:93)
	at com.intellij.codeInsight.completion.CompletionProgressIndicator$1CalculateItems.run(CompletionProgressIndicator.java:813)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$0(CompletionThreading.java:108)
	at com.intellij.openapi.application.impl.ApplicationImpl.runReadAction(ApplicationImpl.java:931)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$null$1(CompletionThreading.java:105)
	at com.intellij.openapi.progress.impl.CoreProgressManager.lambda$runProcess$1(CoreProgressManager.java:176)
	at com.intellij.openapi.progress.impl.CoreProgressManager.registerIndicatorAndRun(CoreProgressManager.java:556)
	at com.intellij.openapi.progress.impl.CoreProgressManager.executeProcessUnderProgress(CoreProgressManager.java:501)
	at com.intellij.openapi.progress.impl.ProgressManagerImpl.executeProcessUnderProgress(ProgressManagerImpl.java:66)
	at com.intellij.openapi.progress.impl.CoreProgressManager.runProcess(CoreProgressManager.java:163)
	at com.intellij.codeInsight.completion.AsyncCompletion.lambda$startThread$2(CompletionThreading.java:103)
	at com.intellij.openapi.application.impl.ApplicationImpl$2.run(ApplicationImpl.java:334)
	at java.util.concurrent.Executors$RunnableAdapter.call(Executors.java:511)
	at java.util.concurrent.FutureTask.run(FutureTask.java:266)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1142)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:617)
	at java.lang.Thread.run(Thread.java:745)

**Comment by kayler-renslow** [comment] 2017-05-29 17:02
It appears IntelliJ did some optimizations or something behind the scenes. I'm not really sure what they did though.

**Comment by Justin99b** [comment] 2017-05-29 17:21
@kayler-renslow Cant you help me :) ? which version of intellij works the best ? i usaly use eclipse so yeah

**Comment by kayler-renslow** [comment] 2017-05-29 17:44
I'm not sure what the issue is. It may take a while to fix the issue. You can try previous versions of IntelliJ, but it could be my code to. I'm investigating this right now.

**Comment by kayler-renslow** [comment] 2017-05-29 17:56
I've identified the issue. It isn't intellij

**Comment by Justin99b** [comment] 2017-05-29 17:58
@kayler-renslow Jo thanks you alot for trying fixing it  i REALY respect your work you done there ^^ its a little pain in the ass to use notepad++ with sqf.

**Comment by Justin99b** [comment] 2017-05-29 18:03
@kayler-renslow when do you want to update the plugin ;) ?

**Comment by kayler-renslow** [comment] 2017-05-29 18:03
When I fix the issue :)

**Comment by Justin99b** [comment] 2017-05-29 18:06
@kayler-renslow haha :D what version can i use without a problem ?

**Comment by kayler-renslow** [comment] 2017-05-29 18:28
Fixed in commit https://github.com/kayler-renslow/arma-intellij-plugin/commit/09a4de106b0f8cead0c1024d0b0140b5e41c710a .

Fixed in release 1.0.9

**Closed as completed by kayler-renslow** 2017-05-29 18:28 UTC
Labels: bug

**Comment by Justin99b** [comment] 2017-05-29 18:32
OMG i love you :D
